### PR TITLE
fix: fix php 8.2 deprecation error

### LINKED ISSUE #817: Creation of dynamic property MyParcelNL\Magento\Model\Settings\AccountSettings::$shop is deprecated
### Plugin version

4.11.1

### Magento version

2.4.6-p3

### PHP version

8.2

### What went wrong?

Different parts on the modules crash because of: Creation of dynamic property MyParcelNL\Magento\Model\Settings\AccountSettings::$shop is deprecated

This is due PHP 8.2 deprecation of dynamic properties

### Reproduction steps

1. Navigate to backend -> MyParcel
2. Click on the PostNL section. Its gives an error output.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Aquive**
Resolves #817

### CODE REVIEW

File: Model/Settings/AccountSettings.php [hunk 1]
```diff
@@ -32,6 +32,26 @@ class AccountSettings extends BaseModel
         'carrier_configurations',
     ];
```
Comment (Mark-Ernst) [inline Model/Settings/AccountSettings.php:33]: Can you remove this array and remove the attribute definitions in the doc block?

Comment (Aquive) [reply Model/Settings/AccountSettings.php]: Done

**Review by wthijmen — APPROVED** [review]

**Review by Mark-Ernst — APPROVED** [review]
