### PR TITLE
fix: remove attributes on uninstall

### LINKED ISSUE #720: Removing myparcel modules result in product edit exception errors
### Plugin version

4.7.0

### Magento version

2.4.4

### PHP version

7.4

### What went wrong?

I've removed the myparcel module.
When attempting to edit a product, an exeption is thrown.

### Reproduction steps

1. Remove myparcel modules
2. Login admin
3. Move to product and hit edit
4. Exception creates a report

### Relevant log output

```shell
composer remove myparcelnl/magento
./composer.json has been updated
Running composer update myparcelnl/magento
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Lock file operations: 0 installs, 0 updates, 2 removals
  - Removing myparcelnl/magento (4.7.0)
  - Removing myparcelnl/sdk (7.4.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 0 updates, 2 removals
  - Removing myparcelnl/sdk (7.4.4)
  - Removing myparcelnl/magento (4.7.0)
Removing Myparcelnl/Sdk
Removing Myparcelnl/Magento
Generating autoload files
122 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
[u10998dxxxxxx@web0104 public_html]$ php bin/magento cache:clean; rm -rf var/cache/*; rm -rf var/page_cache/*; rm -rf generated/code/*; php bin/magento setup:upgrade && php bin/magento indexer:reindex

php bin/magento cache:clean; rm -rf var/cache/*; rm -rf var/page_cache/*; rm -rf generated/code/*; php bin/magento setup:upgrade && php bin/magento indexer:reindex
Cleaned cache types:


Now perform the product edit, and this is the resulting report
There has been an error processing your request
Exception printing is disabled by default for security reasons.
Error log record number: e7d4129bbdf0dda6a37f183892eb6efeb62cf0d449dc2bb1791c314827257a9e


cat report:

{"0":"Class MyParcelNL\\Magento\\Model\\Source\\FitInMailboxOptions does not exist","1":"#1 Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor() called at [vendor\/magento\/framework\/ObjectManager\/Definition\/Runtime.php:54]\n#2 Magento\\Framework\\ObjectManager\\Definition\\Runtime->getParameters() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:48]\n#3 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:56]\n#4 Magento\\Framework\\ObjectManager\\ObjectManager->create() called at [vendor\/magento\/framework\/Validator\/UniversalFactory.php:36]\n#5 Magento\\Framework\\Validator\\UniversalFactory->create() called at [vendor\/magento\/module-eav\/Model\/Entity\/Attribute\/AbstractAttribute.php:642]\n#6 Magento\\Eav\\Model\\Entity\\Attribute\\AbstractAttribute->getSource() called at [generated\/code\/Magento\/Catalog\/Model\/ResourceModel\/Eav\/Attribute\/Interceptor.php:824]\n#7 Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor->getSource() called at [vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav.php:690]\n#8 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav->setupAttributeMeta() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#9 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#10 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#11 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav\/Interceptor.php:59]\n#12 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav\\Interceptor->setupAttributeMeta() called at [vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav.php:404]\n#13 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav->getContainerChildren() called at [generated\/code\/Magento\/Catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav\/Interceptor.php:41]\n#14 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav\\Interceptor->getContainerChildren() called at [vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav.php:379]\n#15 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav->addContainerChildren() called at [generated\/code\/Magento\/Catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav\/Interceptor.php:32]\n#16 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav\\Interceptor->addContainerChildren() called at [vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav.php:355]\n#17 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav->getAttributesMeta() called at [vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav.php:315]\n#18 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav->modifyMeta() called at [generated\/code\/Magento\/Catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav\/Interceptor.php:23]\n#19 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav\\Interceptor->modifyMeta() called at [vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/ProductDataProvider.php:73]\n#20 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\ProductDataProvider->getMeta() called at [vendor\/magento\/framework\/View\/Element\/UiComponentFactory.php:330]\n#21 Magento\\Framework\\View\\Element\\UiComponentFactory->mergeMetadata() called at [vendor\/magento\/framework\/View\/Element\/UiComponentFactory.php:231]\n#22 Magento\\Framework\\View\\Element\\UiComponentFactory->create() called at [vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php:140]\n#23 Magento\\Framework\\View\\Layout\\Generator\\UiComponent->generateComponent() called at [vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php:103]\n#24 Magento\\Framework\\View\\Layout\\Generator\\UiComponent->process() called at [vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php:93]\n#25 Magento\\Framework\\View\\Layout\\GeneratorPool->process() called at [vendor\/magento\/framework\/View\/Layout.php:365]\n#26 Magento\\Framework\\View\\Layout->generateElements() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:68]\n#27 Magento\\Framework\\View\\Layout\\Interceptor->generateElements() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:129]\n#28 Magento\\Framework\\View\\Layout\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Page\/Builder.php:65]\n#29 Magento\\Framework\\View\\Page\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:65]\n#30 Magento\\Framework\\View\\Layout\\Builder->build() called at [vendor\/magento\/framework\/View\/Layout.php:271]\n#31 Magento\\Framework\\View\\Layout->build() called at [vendor\/magento\/framework\/View\/Layout.php:896]\n#32 Magento\\Framework\\View\\Layout->getBlock() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:293]\n#33 Magento\\Framework\\View\\Layout\\Interceptor->getBlock() called at [vendor\/magento\/module-backend\/Model\/View\/Result\/Page.php:26]\n#34 Magento\\Backend\\Model\\View\\Result\\Page->setActiveMenu() called at [generated\/code\/Magento\/Backend\/Model\/View\/Result\/Page\/Interceptor.php:23]\n#35 Magento\\Backend\\Model\\View\\Result\\Page\\Interceptor->setActiveMenu() called at [vendor\/magento\/module-catalog\/Controller\/Adminhtml\/Product\/Edit.php:82]\n#36 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit->execute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#37 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#38 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#39 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/Edit\/Interceptor.php:23]\n#40 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:111]\n#41 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:151]\n#42 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#43 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#44 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [app\/code\/WeltPixel\/Backend\/Plugin\/Utility.php:76]\n#45 WeltPixel\\Backend\\Plugin\\Utility->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#46 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:145]\n#47 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#48 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#49 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/Edit\/Interceptor.php:32]\n#50 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:245]\n#51 Magento\\Framework\\App\\FrontController->getActionResponse() called at [vendor\/magento\/framework\/App\/FrontController.php:212]\n#52 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:147]\n#53 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#54 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#55 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#56 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:23]\n#57 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#58 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:264]\n#59 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:30]\n","url":"\/aed90z0t\/catalog\/product\/edit\/id\/76\/key\/67e2f2f9a86c22fbf9355ffceaa3954ed1fabc903a4460c8e04da40c8ab7557e\/","script_name":"\/pub\/index.php","report_id":"e7d4129bbdf0dda6a37f183892eb6efeb62cf0d449dc2bb1791c314827257a9e"}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Mark-Ernst**
Resolves #720

### CODE REVIEW

File: Setup/Uninstall.php [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+use Magento\Framework\App\ObjectManager;
+use Magento\Framework\Setup\ModuleContextInterface;
+use Magento\Framework\Setup\SchemaSetupInterface;
+use Magento\Framework\Setup\UninstallInterface;
+
+class Uninstall implements UninstallInterface
+{
+    /**
+     * @throws \Exception
+     */
```
Comment (EdieLemoine) [inline Setup/Uninstall.php:18]:
```suggestion
		 * @SuppressWarnings(PHPMD.UnusedLocalVariable)
     */
```

**Review by EdieLemoine — CHANGES_REQUESTED** [review]

**Review by wthijmen — APPROVED** [review]

**Review by joerivanveen — APPROVED** [review]

**Review by EdieLemoine — APPROVED** [review]
