### PR TITLE
Http 500 error due to get max company name

### LINKED ISSUE #360: HTTP 500 error due to getMaxCompanyName related issues
I found 2 related issues in version 2.5.6. Both cause this error:
Sales => Orders => open order => Print Label => HTTP 500 error.

Issue 1:
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to MyParcelNL\Magento\Model\Source\DefaultOptions::getMaxCompanyName() must be of the type string, null given, called in vendor/myparcelnl/magento/Model/Sales/MyParcelTrackTrace.php on line 143 and defined in vendor/myparcelnl/magento/Model/Source/DefaultOptions.php:86

This happens for addresses where the company name is not filled out by the customer, causing getMaxCompanyName() to be called with parameter NULL.

Issue 2: 
PHP message: PHP Fatal error:  Uncaught Error: Undefined class constant 'COMPANY_NAME_MAX_LENGTH' in vendor/myparcelnl/magento/Model/Source/DefaultOptions.php:88

Problem started with commits c0b2a0374ea55d39f65c3604c3d096d49f9ea66a and a28b85464cfd39775266b6351d8d7d22be7cdc08

### PR DESCRIPTION
**Pull request by RichardPerdaan**
Fixes #360

### CODE REVIEW

File: Model/Source/DefaultOptions.php [hunk 1]
```diff
@@ -91,7 +91,7 @@ public function getDefault($option)
      */
     public function getMaxCompanyName(?string $company): ?string
     {
-        if (strlen((string) $company) >= self::COMPANY_NAME_MAX_LENGTH) {
+        if ($company != null && (strlen($company) >= self::COMPANY_NAME_MAX_LENGTH)) {
```
Comment (EdieLemoine) [inline Model/Source/DefaultOptions.php:94]: waarom weak equality?

Comment (RichardPerdaan) [inline Model/Source/DefaultOptions.php:94]:
```suggestion
        if ($company !== null && (strlen($company) >= self::COMPANY_NAME_MAX_LENGTH)) {
```

Comment (RichardPerdaan) [reply Model/Source/DefaultOptions.php]: goed gezien
