### PR TITLE
fix: only set country if currentCountry has value

### LINKED ISSUE #789: Error: getCurrentCountry(): Return value must be of type string
### Plugin version

4.11.0

### Magento version

2.4.5-p1

### PHP version

8.1

### What went wrong?

When I have an order I want to recreate it via the button 'Opnieuw bestellen'.

After that I get an error message: 
```
[2023-11-22T12:00:49.852892+00:00] main.CRITICAL: TypeError: MyParcelNL\Magento\Model\Sales\Package::getCurrentCountry(): Return value must be of type string, null returned in myparcelnl/magento/Model/Sales/Package.php:240
Stack trace:
#0 myparcelnl/magento/Model/Sales/Repository/PackageRepository.php(134): MyParcelNL\Magento\Model\Sales\Package->getCurrentCountry()
#1 myparcelnl/magento/Model/Sales/Repository/PackageRepository.php(90): MyParcelNL\Magento\Model\Sales\Repository\PackageRepository->fitInDigitalStamp()
#2 myparcelnl/magento/Model/Rate/Result.php(190): MyParcelNL\Magento\Model\Sales\Repository\PackageRepository->selectPackageType()
#3 myparcelnl/magento/Model/Rate/Result.php(120): MyParcelNL\Magento\Model\Rate\Result->addMyParcelRates()
#4 magento/module-offline-shipping/Model/Carrier/Freeshipping.php(114): MyParcelNL\Magento\Model\Rate\Result->append()
#5 magento/module-shipping/Model/Shipping.php(335): Magento\OfflineShipping\Model\Carrier\Freeshipping->collectRates()
#6 magento/module-shipping/Model/Shipping.php(244): Magento\Shipping\Model\Shipping->collectCarrierRates()
#7 magento/module-quote/Model/Quote/Address.php(1077): Magento\Shipping\Model\Shipping->collectRates()
#8 magento/module-quote/Model/Quote/Address.php(1004): Magento\Quote\Model\Quote\Address->requestShippingRates()
#9 magento/module-quote/Model/Quote/Address/Total/Shipping.php(83): Magento\Quote\Model\Quote\Address->collectShippingRates()
```

Why do I get this error and how can I solve this?

### Reproduction steps

1. Select an order in Magento-admin
2. Click on 'Opnieuw bestellen'
3. Error is shown

### Relevant log output

```shell
[2023-11-22T12:00:49.852892+00:00] main.CRITICAL: TypeError: MyParcelNL\Magento\Model\Sales\Package::getCurrentCountry(): Return value must be of type string, null returned in myparcelnl/magento/Model/Sales/Package.php:240
Stack trace:
#0 myparcelnl/magento/Model/Sales/Repository/PackageRepository.php(134): MyParcelNL\Magento\Model\Sales\Package->getCurrentCountry()
#1 myparcelnl/magento/Model/Sales/Repository/PackageRepository.php(90): MyParcelNL\Magento\Model\Sales\Repository\PackageRepository->fitInDigitalStamp()
#2 myparcelnl/magento/Model/Rate/Result.php(190): MyParcelNL\Magento\Model\Sales\Repository\PackageRepository->selectPackageType()
#3 myparcelnl/magento/Model/Rate/Result.php(120): MyParcelNL\Magento\Model\Rate\Result->addMyParcelRates()
#4 magento/module-offline-shipping/Model/Carrier/Freeshipping.php(114): MyParcelNL\Magento\Model\Rate\Result->append()
#5 magento/module-shipping/Model/Shipping.php(335): Magento\OfflineShipping\Model\Carrier\Freeshipping->collectRates()
#6 magento/module-shipping/Model/Shipping.php(244): Magento\Shipping\Model\Shipping->collectCarrierRates()
#7 magento/module-quote/Model/Quote/Address.php(1077): Magento\Shipping\Model\Shipping->collectRates()
#8 magento/module-quote/Model/Quote/Address.php(1004): Magento\Quote\Model\Quote\Address->requestShippingRates()
#9 magento/module-quote/Model/Quote/Address/Total/Shipping.php(83): Magento\Quote\Model\Quote\Address->collectShippingRates()
#10 magento/module-quote/Model/Quote/TotalsCollector.php(261): Magento\Quote\Model\Quote\Address\Total\Shipping->collect()
#11 magento/module-quote/Model/Quote/TotalsCollector.php(156): Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals()
#12 magento/module-quote/Model/Quote.php(2015): Magento\Quote\Model\Quote\TotalsCollector->collect()
#13 magento/module-sales/Model/AdminOrder/Create.php(1624): Magento\Quote\Model\Quote->collectTotals()
#14 magento/module-sales/Model/AdminOrder/Create.php(1612): Magento\Sales\Model\AdminOrder\Create->collectRates()
#15 magento/module-sales/Model/AdminOrder/Create.php(596): Magento\Sales\Model\AdminOrder\Create->collectShippingRates()
#16 magento/module-sales/Controller/Adminhtml/Order/Create/Reorder.php(119): Magento\Sales\Model\AdminOrder\Create->initFromOrder()
#17 magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder->execute()
#18 magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->___callParent()
#19 magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->Magento\Framework\Interception\{closure}()
#20 generated/code/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->___callPlugins()
#21 magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->execute()
#22 magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#23 magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#24 magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->___callParent()
#25 magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->Magento\Framework\Interception\{closure}()
#26 magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#27 magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->Magento\Framework\Interception\{closure}()
#28 generated/code/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->___callPlugins()
#29 magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->dispatch()
#30 magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#31 magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#32 magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#33 magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#34 magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#35 generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#36 magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#37 magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#38 pub/index.php(65): Magento\Framework\App\Bootstrap->run()
#39 {main} [] []
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wthijmen**
Resolves #789

### CODE REVIEW

File: Model/Sales/Package.php [hunk 1]
```diff
@@ -245,6 +245,8 @@ public function getCurrentCountry(): string
      */
     public function setCurrentCountry(?string $currentCountry): void
     {
-        $this->currentCountry = $currentCountry;
+        if ($currentCountry !== null) {
```
Comment (EdieLemoine) [inline Model/Sales/Package.php:248]: unhappy flow eerst

**Review by EdieLemoine — CHANGES_REQUESTED** [review]
dit is geen refactor

**Review by Mark-Ernst — APPROVED** [review]

**Review by joerivanveen — APPROVED** [review]

**Review by EdieLemoine — APPROVED** [review]

**Review by EdieLemoine — APPROVED** [review]
